services:
  caddy:
    image: docker.io/caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "${CADDY_HTTP_PORT:-8080}:80"
    volumes:
      - $PWD/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - proxy
  
  webhook:
    build:
      context: ./webhooks
      dockerfile: Dockerfile
    container_name: webhook
    restart: unless-stopped
    user: root # to access the docker socket
    environment:
      - WEBHOOK_TOKEN=${WEBHOOK_TOKEN}
    volumes:
      - $PWD/webhooks:/etc/webhook:ro
      - $PWD/:/repos/infra
      - ${PROJECTS_DIR}:/repos/projects:ro
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock
    command: ["-hooks=/etc/webhook/hooks.json", "-verbose", "-template"]
    networks:
      - proxy

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy:
    external: true
